# Generated by Django 5.1.4 on 2025-04-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_authenticate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userauthentication",
            name="account_status",
        ),
    ]
