# Generated by Django 5.0.3 on 2024-11-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("assigned_date", models.DateField(auto_now=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=True)),
            ],
        ),
    ]
