# Generated by Django 5.0.3 on 2024-11-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="assigned_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
