# Generated by Django 5.0.3 on 2024-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0002_alter_tasklist_assigned_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="assigned_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
