# Generated by Django 5.0.3 on 2024-11-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0006_alter_tasklist_completed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
