# Generated by Django 5.2 on 2025-04-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_upvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="description",
        ),
    ]
