# Generated by Django 5.1.4 on 2025-04-09 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0004_answer_likes_answer_updated_at_alter_answer_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="votes",
            field=models.ManyToManyField(
                related_name="voted", through="qna.UpVote", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="upvote",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ans_votes",
                to="qna.answer",
            ),
        ),
    ]
