# Generated by Django 5.0.3 on 2024-11-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0005_alter_tasklist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="completed_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
